// AUTO-GENERATED by scripts/gen-favorites.mjs — do not edit by hand.
// Pre-loaded ("favorite") tags baked in so they render instantly without the
// slow barbershoptags.com API. To change the list, edit FAVORITE_IDS in
// scripts/gen-favorites.mjs and re-run `node scripts/gen-favorites.mjs`.
import type { Tag } from './types';

export const FAVORITE_TAGS: Tag[] = [
  {
    "id": 1652,
    "title": "If Only For A Day",
    "altTitle": "",
    "arranger": "Josh L.",
    "parts": 4,
    "type": "Barbershop",
    "writKey": "Major:Ab",
    "rating": 3.3158,
    "ratingCount": 608,
    "downloaded": 9695,
    "notes": "The name doesn't match the tag, but the barbershop world knows it by that name.  The arranger wishes us to know that it wasn't his idea.  :p",
    "lyrics": "If only for a day, you were my baby girl.  Good-bye...",
    "sheetMusic": "https://www.barbershoptags.com/dbaction.php?action=DownloadFile&dbase=tags&id=1652&fldname=SheetMusic",
    "sheetMusicType": "pdf",
    "sheetMusicAlt": "https://www.barbershoptags.com/tags/Dead_Baby.pdf",
    "voiceTracks": {},
    "allParts": "https://www.barbershoptags.com/dbaction.php?action=DownloadFile&dbase=tags&id=1652&fldname=AllParts",
    "notation": "https://www.barbershoptags.com/dbaction.php?action=DownloadFile&dbase=tags&id=1652&fldname=Notation",
    "notationAlt": "https://www.barbershoptags.com/tags/Dead_Baby.mus",
    "videoCode": null
  },
  {
    "id": 2128,
    "title": "The Dream Tag",
    "altTitle": "",
    "arranger": "Stephan Carlson",
    "parts": 4,
    "type": "Barbershop",
    "writKey": "Major:Eb",
    "rating": 3.3829,
    "ratingCount": 632,
    "downloaded": 25411,
    "notes": "Written and performed by Stephan Carlson.\n\nTranscribed (by the best of his ability) by: John Saylor",
    "lyrics": "If this is a dream, then leave me to rest. For when I wake my heart shall break. But I'll know your name.",
    "sheetMusic": "https://www.barbershoptags.com/dbaction.php?action=DownloadFile&dbase=tags&id=2128&fldname=SheetMusic",
    "sheetMusicType": "pdf",
    "sheetMusicAlt": "https://www.barbershoptags.com/tags/The_Dream_Tag.pdf",
    "voiceTracks": {
      "Tenor": "https://www.barbershoptags.com/dbaction.php?action=DownloadFile&dbase=tags&id=2128&fldname=Tenor",
      "Lead": "https://www.barbershoptags.com/dbaction.php?action=DownloadFile&dbase=tags&id=2128&fldname=Lead",
      "Bari": "https://www.barbershoptags.com/dbaction.php?action=DownloadFile&dbase=tags&id=2128&fldname=Bari",
      "Bass": "https://www.barbershoptags.com/dbaction.php?action=DownloadFile&dbase=tags&id=2128&fldname=Bass"
    },
    "allParts": "https://www.barbershoptags.com/dbaction.php?action=DownloadFile&dbase=tags&id=2128&fldname=AllParts",
    "notation": "https://www.barbershoptags.com/dbaction.php?action=DownloadFile&dbase=tags&id=2128&fldname=Notation",
    "notationAlt": "https://www.barbershoptags.com/tags/The_Dream_Tag.sib",
    "videoCode": "XXeypRQJK2g"
  },
  {
    "id": 2275,
    "title": "Like Leaves We'll Fall In Love",
    "altTitle": "",
    "arranger": "Jake Tickner",
    "parts": 4,
    "type": "Barbershop",
    "writKey": "Major:Ab",
    "rating": 3.3735,
    "ratingCount": 937,
    "downloaded": 66694,
    "notes": "",
    "lyrics": "(Will fall)\nLike leaves in fall we'll fall in love (in love).",
    "sheetMusic": "https://www.barbershoptags.com/dbaction.php?action=DownloadFile&dbase=tags&id=2275&fldname=SheetMusic",
    "sheetMusicType": "pdf",
    "sheetMusicAlt": "https://www.barbershoptags.com/tags/Like_Leaves_will_Fall_in_Love.pdf",
    "voiceTracks": {
      "Tenor": "https://www.barbershoptags.com/dbaction.php?action=DownloadFile&dbase=tags&id=2275&fldname=Tenor",
      "Lead": "https://www.barbershoptags.com/dbaction.php?action=DownloadFile&dbase=tags&id=2275&fldname=Lead",
      "Bari": "https://www.barbershoptags.com/dbaction.php?action=DownloadFile&dbase=tags&id=2275&fldname=Bari",
      "Bass": "https://www.barbershoptags.com/dbaction.php?action=DownloadFile&dbase=tags&id=2275&fldname=Bass"
    },
    "allParts": "https://www.barbershoptags.com/dbaction.php?action=DownloadFile&dbase=tags&id=2275&fldname=AllParts",
    "notation": null,
    "notationAlt": null,
    "videoCode": "Hye4OcPVXsE"
  },
  {
    "id": 20,
    "title": "When I Leave the World Behind",
    "altTitle": "",
    "arranger": "",
    "parts": 4,
    "type": "Barbershop",
    "writKey": "Major:Eb",
    "rating": 3.3691,
    "ratingCount": 1108,
    "downloaded": 80086,
    "notes": "This tag is very easy to learn while sounding impressive with the harmonies. easy to teach as well.",
    "lyrics": "",
    "sheetMusic": "https://www.barbershoptags.com/dbaction.php?action=DownloadFile&dbase=tags&id=20&fldname=SheetMusic",
    "sheetMusicType": "gif",
    "sheetMusicAlt": "https://www.barbershoptags.com/tags/When_I_Leave_the_World_Behind.gif",
    "voiceTracks": {
      "Tenor": "https://www.barbershoptags.com/dbaction.php?action=DownloadFile&dbase=tags&id=20&fldname=Tenor",
      "Lead": "https://www.barbershoptags.com/dbaction.php?action=DownloadFile&dbase=tags&id=20&fldname=Lead",
      "Bari": "https://www.barbershoptags.com/dbaction.php?action=DownloadFile&dbase=tags&id=20&fldname=Bari",
      "Bass": "https://www.barbershoptags.com/dbaction.php?action=DownloadFile&dbase=tags&id=20&fldname=Bass"
    },
    "allParts": "https://www.barbershoptags.com/dbaction.php?action=DownloadFile&dbase=tags&id=20&fldname=AllParts",
    "notation": null,
    "notationAlt": null,
    "videoCode": "wmQllDlAaFc"
  }
];

export const FAVORITE_TAG_IDS = new Set<number>(FAVORITE_TAGS.map((t) => t.id));

export function getFavoriteTag(id: number): Tag | undefined {
  return FAVORITE_TAGS.find((t) => t.id === id);
}
